title: Mahimashree Prabhakar
logo: /Assets/img/Headshot.png
description : Electrical and Electronics Engineer
description : Email: Mahimashreeprabhakar@gmail.com
#show_downloads: true
theme : jekyll-theme-minimal
