title: Mahimashree Prabhakar
logo: /Assets/img/Headshot.png
description : Electrical and Electronics Engineer
description : Email: Mahimashreeprabhakar@gmail.com
description : Twitter : @mahimashree_
description : LinkeDin : https://www.linkedin.com/in/mahimashree-prabhakar-916710138/
#show_downloads: true
theme : jekyll-theme-minimal
